version: '3.8' # We will use 3.8 version of docker-compose
services:
  db:
    image: postgres:12.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ## Remember stop or remove container to change user and password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 

  web:
    build:
      context: . # current dir as build context
      args:
        BUNDLE_WITHOUT: 'production test'
        FOLDERS_TO_REMOVE: 'tmp/cache log/* vendor/assets lib/assets test public/packs-test'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/code
    #  - gem_cache:/usr/local/bundle/gems
      - node_modules:/code/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
 # gem_cache:
  node_modules:

